### ISSUE TITLE
Benchmarks should be fair

### ISSUE THREAD

**Issue by littledivy** [littledivy/autopilot-deno#23]
So currently we have a cute benchmarking system. Simply, run the method and calculate the time taken.

The problem:
Some methods like `alert` are only completed when the user clicks Ok...which is expected in real life scenario but that disrupts the benchmarks by many milliseconds/secs!

We need to come up with another op that mocks the alert methods the closest way possible.

**Comment by divy-work** [comment]
Switching to async ops #25

**Comment by littledivy** [comment]
No longer holds significance.
