### ISSUE TITLE
core.setAsyncHandler is not a function

### ISSUE THREAD

**Issue by abdullahIsa** [littledivy/autopilot-deno#39]
![Screenshot from 2021-04-19 13-41-00](https://user-images.githubusercontent.com/49385380/115186830-f2cef780-a114-11eb-9946-3aea1275ff28.png)

Hello, currently getting this error, would be great to have it checked, thanks.

**Comment by littledivy** [comment]
Fixed in the latest autopilot `0.3.0` (compatible with Deno 1.12.1).
