### ISSUE TITLE
FFI

### ISSUE THREAD

**Issue by littledivy** [littledivy/autopilot-deno#41]
Plugins are dead. We need to move to FFI once passing buffer support is added. This module should still work up until Deno 1.12.2

**Comment by nnmrts** [comment]
Hey! Just found out plugins got removed in 1.13 after I wanted to try out autopilot.

I'm just curious, what is "passing buffer support" and where can I track it's progress?

Thanks!

**Comment by littledivy** [comment]
@nnmrts There is an open PR https://github.com/denoland/deno/pull/11648
